# -*- coding: utf-8 -*-
"""Pytorch workflow 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhGRXAeNrd8p8lJo4PIhx0jXCOJrY5WJ
"""

import torch
import matplotlib.pyplot as plt
import torch.nn as nn

device = "cuda" if torch.cuda.is_available() else "cpu"

# Create *known* parameters
weight = 0.3
bias = 0.9

# Create data
start = 0
end = 1
step = 0.01
X = torch.arange(start, end, step).unsqueeze(dim=1)
Y = weight * X + bias

X[:10], Y[:10]

X_split = int(0.8 * len(X))
X_train, Y_train = X[:X_split], Y[:X_split]
X_test, Y_test = X[X_split:], Y[X_split:]

len(X_train), len(Y_train), len(X_test), len(Y_test)

def plot_predictions( train_data=X_train,
                      train_labels=Y_train,
                      test_data=X_test,
                      test_labels=Y_test,
                      predictions=None):


  plt.figure(figsize=(10,7))
  plt.scatter(train_data, train_labels, c='b', s=4, label='Training label')
  plt.scatter(test_data, test_labels, c='g', s=4, label='Testing label')

  if predictions is not None:

    plt.scatter(test_data, predictions, c="r", s=4, label="Predictions")

  # Show the legend
    plt.legend(prop={"size": 14});

plot_predictions()

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, dtype = torch.float), requires_grad = True)
    self.bias = nn.Parameter(torch.randn(1, dtype = torch.float), requires_grad = True)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias

torch.manual_seed(42)

model_1 = LinearRegressionModel()

model_1.state_dict()

with torch.inference_mode():
  y_preds = model_1(X_test)

  plot_predictions(predictions = y_preds)

#create a loss function
loss_fn = nn.L1Loss()

#set an optimizer
optimizer = torch.optim.SGD(params = model_1.parameters(), lr = 0.01)

torch.manual_seed(42)

epochs = 300

X_train = X_train.to(device)
Y_train = Y_train.to(device)
X_test = X_test.to(device)
Y_test = Y_test.to(device)


train_loss_values = []
test_loss_values = []
epoch_count = []

for epoch in range(epochs):
  model_1.train()

  y_preds = model_1(X_train)

  train_loss = loss_fn(y_preds, Y_train)
  train_loss_values.append(train_loss)

  optimizer.zero_grad()

  train_loss.backward()

  optimizer.step()

  model_1.eval()

  with torch.inference_mode():
    test_pred = model_1(X_test)
    test_loss = loss_fn(test_pred, Y_test)
    test_loss_values.append(test_loss)

    if epoch % 10 == 0:
      epoch_count.append(epoch)
      train_loss_values.append(train_loss.detach().numpy())
      test_loss_values.append(test_loss.detach().numpy())
      print(f"Epoch: {epoch} | MAE Train Loss: {train_loss} | MAE Test Loss: {test_loss} ")

model_1.eval()

with torch.inference_mode():
  y_preds = model_1(X_test)
y_preds

plot_predictions(predictions=y_preds)

from pathlib import Path

# 1. Create models directory
MODEL_PATH = Path("models")
MODEL_PATH.mkdir(parents=True, exist_ok=True)

# 2. Create model save path
MODEL_NAME = "01_pytorch_workflow_model_1.pth"
MODEL_SAVE_PATH = MODEL_PATH / MODEL_NAME

# 3. Save the model state dict
print(f"Saving model to: {MODEL_SAVE_PATH}")
torch.save(obj=model_1.state_dict(), # only saving the state_dict() only saves the models learned parameters
           f=MODEL_SAVE_PATH)

!ls -l models/01_pytorch_workflow_model_1.pth

loaded_model_1 = LinearRegressionModel()

loaded_model_1.load_state_dict(torch.load(f='models/01_pytorch_workflow_model_1.pth'))

loaded_model_1.eval()

with torch.inference_mode():
    loaded_model_preds = loaded_model_1(X_test)

y_preds == loaded_model_preds