# -*- coding: utf-8 -*-
"""Tensor_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pj46MFPZ_I9FbAAJCLcYXSqI6O9M-RH
"""

import torch


'''Number 2'''
tensor_A = torch.rand(size=(7,7))
tensor_A

tensor_B = torch.rand(size=(1,7))
tensor_B


'''Number 3'''
tensor_AB = torch.matmul(tensor_A, tensor_B.T)
tensor_AB


'''Number 4'''
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(size=(7,7))

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(size=(1,7))

tensor_AB_rseed = torch.matmul(tensor_A, tensor_B.T)
tensor_AB_rseed, tensor_AB_rseed.shape


'''Number 5'''
torch.cuda.manual_seed(1234)


'''Number 6'''
import torch
import random

torch.manual_seed(1234)
tensor_C = torch.rand(size=(2,3))

torch.manual_seed(1234)
tensor_D = torch.rand(size=(2,3))

tensor_C_GPU = tensor_C.to(device = "cuda")
tensor_D_GPU = tensor_D.to(device = "cuda")

tensor_C_GPU, tensor_D_GPU


'''Number 7'''
tensor_CD_GPU = torch.matmul(tensor_C_GPU, tensor_D_GPU.T)
tensor_CD_GPU


'''Number 8'''
tensor_CD_GPU.max(), tensor_CD_GPU.min()


'''Number 9'''
tensor_CD_GPU_argmax = tensor_CD_GPU.argmax()
tensor_CD_GPU_argmin = tensor_CD_GPU.argmin()
tensor_CD_GPU_argmax, tensor_CD_GPU_argmin


'''Number 10'''
torch.manual_seed(7)
tensor_E = torch.rand(size=(1,1,1,10))
tensor_E_squeeze = tensor_E.squeeze()
print(f"First tensor:\n{tensor_E}\n")
print(f"First tensor shape:\n{tensor_E.shape}\n")
print(f"Squeezed tensor:\n{tensor_E_squeeze}\n")
print(f"Squeezed tensor shape:\n{tensor_E_squeeze.shape}")